### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by NorthernMan54** [neonightmare/homebridge-yamaha#17]
I was making some changes to this, and I noticed that there are a number of forks and that the primary owner of the repository hasn't been made any changes in the past 12 months.   Should we make a new version, with a different name and merge all the forks back together again?

**Comment by florian-muc** [comment]
That would be absolutely awesome! I'm using some obscure unreleased change right now, but I don't trust my own skills to build a new version. Plus, the version I use still is rather buggy.

**Comment by ZaubererMD** [comment]
I stopped development of my fork because I felt like HomeKit does not offer me enough freedom, plus it restricts me to using apple devices. I am developing my own software now for private use.
If you want to incorporate any changes made in my fork feel free to do so and please let me know. I will probably close my fork as soon as you no longer have use for it.

**Comment by NorthernMan54** [comment]
@ZaubererMD Okay, please close your fork, and I will continue on with this.   Tks for your great work on this

**Comment by NorthernMan54** [comment]
I think I'm going to focus on making my highest used functions available via the Home App and Alexa.  While it won't be able to offer the extra features of the Eve app, it would make it more accessible.

**Comment by abko** [comment]
@NorthernMan54 Hello, I am a bit of a novice on NodeJS, Homebridge and GitHub. I downloaded your latest fork via (git) Clone to my Raspberry PI and tried to use it via npm (install -g homebridge-yamaha).

When running homebridge I am receiving errors on line 148 related to getAvailableZones() not being available. I hope you don't mind me asking. Am I missing a step in trying to use your fork on my homebridge setup?

Note reason for using your fork is that I am hoping to get input selection, volume and zones working via HomeKit. The regular Yamaha plugin only offers to switch my receiver on/off. Volume is visible in the Eve app but not functional.

Thanks,
Abko

**Comment by NorthernMan54** [comment]
Can you rerun in DEBUG mode, share the error detail including the trace.

I coded it to create an accessory per zone, and yours may not support zones etc.

**Comment by abko** [comment]
Thanks for your reply. I will figure out how to enable debug and share the results later. I am using it with a Yamaha RX-A3060 which supports multiple zones.

This is what appears in logging without DEBUG enabled:

[4/14/2017, 9:30:32 PM] Homebridge is running on port 51826.
Unhandled rejection TypeError: yamaha.getAvailableZones is not a function
    at YamahaAVRPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha/index.js:148:32)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)

**Comment by abko** [comment]
I have started homebridge using 'DEBUG=* homebridge -D'

Logging is similar to the version above added with addition logging after the main error message, see below.

  EventedHTTPServer Server listening on port 51826 +0ms
[4/14/2017, 9:50:38 PM] Homebridge is running on port 51826.
Unhandled rejection TypeError: yamaha.getAvailableZones is not a function
    at YamahaAVRPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha/index.js:148:32)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:668:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)

  YamahaAVR Got volume percent of 47% +0ms
  EventedHTTPServer [::ffff:192.168.1.60] New connection from client +54s
  EventedHTTPServer [::ffff:192.168.1.60] HTTP server listening on port 32904 +20ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP request: /pair-verify +87ms
  HAPServer [CF:21:3D:E3:CE:38] HAP Request: POST /pair-verify +7ms
  HAPServer [CF:21:3D:E3:CE:38] Pair verify step 1/2 +28ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP Response is finished +146ms
  EventedHTTPServer [::ffff:192.168.1.60] Client connection closed +168ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP connection was closed +15ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP server was closed +7ms
  EventedHTTPServer [::ffff:192.168.1.69] New connection from client +11s
  EventedHTTPServer [::ffff:192.168.1.69] HTTP server listening on port 35234 +6ms
  EventedHTTPServer [::ffff:192.168.1.69] HTTP request: /pair-verify +87ms
  HAPServer [CF:21:3D:E3:CE:38] HAP Request: POST /pair-verify +3ms
  HAPServer [CF:21:3D:E3:CE:38] Pair verify step 1/2 +8ms
  EventedHTTPServer [::ffff:192.168.1.69] HTTP Response is finished +70ms
  EventedHTTPServer [::ffff:192.168.1.69] Client connection closed +34ms
  EventedHTTPServer [::ffff:192.168.1.69] HTTP connection was closed +8ms
  EventedHTTPServer [::ffff:192.168.1.69] HTTP server was closed +4ms
  EventedHTTPServer [::ffff:192.168.1.56] New connection from client +989ms
  EventedHTTPServer [::ffff:192.168.1.56] HTTP server listening on port 45395 +3ms
  EventedHTTPServer [::ffff:192.168.1.56] HTTP request: /pair-verify +15ms
  HAPServer [CF:21:3D:E3:CE:38] HAP Request: POST /pair-verify +2ms
  HAPServer [CF:21:3D:E3:CE:38] Pair verify step 1/2 +5ms
  EventedHTTPServer [::ffff:192.168.1.56] HTTP Response is finished +37ms
  EventedHTTPServer [::ffff:192.168.1.56] Client connection closed +25ms
  EventedHTTPServer [::ffff:192.168.1.56] HTTP connection was closed +7ms
  EventedHTTPServer [::ffff:192.168.1.56] HTTP server was closed +3ms
  EventedHTTPServer [::ffff:192.168.1.56] New connection from client +32s
  EventedHTTPServer [::ffff:192.168.1.56] HTTP server listening on port 41012 +4ms
  EventedHTTPServer [::ffff:192.168.1.56] HTTP request: /pair-verify +22ms
  HAPServer [CF:21:3D:E3:CE:38] HAP Request: POST /pair-verify +2ms
  HAPServer [CF:21:3D:E3:CE:38] Pair verify step 1/2 +7ms
  EventedHTTPServer [::ffff:192.168.1.56] HTTP Response is finished +73ms
  EventedHTTPServer [::ffff:192.168.1.56] Client connection closed +47ms
  EventedHTTPServer [::ffff:192.168.1.56] HTTP connection was closed +6ms
  EventedHTTPServer [::ffff:192.168.1.56] HTTP server was closed +4ms
  EventedHTTPServer [::ffff:192.168.1.60] New connection from client +35s
  EventedHTTPServer [::ffff:192.168.1.60] HTTP server listening on port 41663 +3ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP request: /pair-verify +23ms
  HAPServer [CF:21:3D:E3:CE:38] HAP Request: POST /pair-verify +3ms
  HAPServer [CF:21:3D:E3:CE:38] Pair verify step 1/2 +6ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP Response is finished +49ms
  EventedHTTPServer [::ffff:192.168.1.60] Client connection closed +32ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP connection was closed +7ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP server was closed +2ms
  EventedHTTPServer [::ffff:192.168.1.60] New connection from client +26s
  EventedHTTPServer [::ffff:192.168.1.60] HTTP server listening on port 36666 +3ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP request: /pair-verify +18ms
  HAPServer [CF:21:3D:E3:CE:38] HAP Request: POST /pair-verify +3ms
  HAPServer [CF:21:3D:E3:CE:38] Pair verify step 1/2 +6ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP Response is finished +54ms
  EventedHTTPServer [::ffff:192.168.1.60] Client connection closed +27ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP connection was closed +6ms
  EventedHTTPServer [::ffff:192.168.1.60] HTTP server was closed +4ms

**Comment by NorthernMan54** [comment]
@abko I found the problem, in my branch I had been also working with a newer version of yamaha-nodes to support my efforts around Zones.  I have sent a pull request for my changes to yamaha-nodejs, and it should be updated shortly.  In the interim please use my version of yamaha-nodejs.

The error is because the stock version of yamaha-nodejs doesn't include this new function I added around zones.

**Comment by abko** [comment]
I am obviously doing something wrong, but I cloned your Yamaha-nodejs fork (git clone) and installed it using npm. I still get the same error. Note I am just starting with nodejs. etc, so probably overlooking something obvious:

Unhandled rejection TypeError: yamaha.getAvailableZones is not a function
    at YamahaAVRPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha/index.js:148:32)

**Comment by NorthernMan54** [comment]
Oh ok, to update the version you need to find where npm had installed the original version of yamaha-nodejs and update that version.   If you installed homebridge-yamaha with the -g option it should have been installed here

/usr/lib/node_modules/homebridge-yamaha/node_modules/yamaha-nodejs

To update this version of yamaha-nodejs, run npm install without the -g option in this directory

/usr/lib/node_modules/homebridge-yamaha

and run

sudo npm install https://github.com/NorthernMan54/yamaha-nodejs

Then restart and everything should be okay

If you look, you are likely to have a second version of yamaha-nodejs in 
/usr/lib/node_modules/yamaha-nodejs  This can be deleted.

**Comment by abko** [comment]
Thanks @NorthernMan54 . Sorry for the slow response. I was not able to pick this up earlier. Your suggestion worked, and now also the latest version is updated.
I do still get a warning, see below, and also it's not clear how to get multiple zones to work. Any hint would be appreciated. 
Thanks again! Abko

[4/22/2017, 11:05:20 AM] Discovery finished, found 1 Yamaha AVR devices.
Unhandled rejection Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at timeoutFunction (/usr/local/lib/node_modules/homebridge-yamaha/index.js:225:13)
    at YamahaAVRPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha/index.js:187:25)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)

**Comment by NorthernMan54** [comment]
I think that is caused by the expected devices config setting. Just remove it from your config.json and try again.

**Comment by abko** [comment]
I thought I solved it earlier, but made an error in installation of the plugin and as a result was running the current master instead of your fork. Now I fixed the installation I run again into the same problem.

I am not sure what you mean with the expected devices config setting. This is what I have for the receiver at the moment:

> "platforms": [
>       {
>           "platform": "YamahaAVR",
>           "name": "Versterker",
>           "play_volume": -48,
>           "setMainInputTo": "Airplay",
>           "show_input_name": "yes"
>       },

**Comment by NorthernMan54** [comment]
Can you share the current error message?

**Comment by abko** [comment]
Its actually slightly different, but might suggest to a similar problem. It gives me the impression it tries to setup something similar for both zones which might conflict.

> /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:228
>       throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
>       ^
> 
> Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 38da4fe6-6494-4905-8d9e-59420949755a
>     at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:228:13)
>     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:367:24)
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
>     at Timeout.timeoutFunction [as _onTimeout] (/usr/local/lib/node_modules/homebridge-yamaha/index.js:225:13)
>     at ontimeout (timers.js:386:14)
>     at tryOnTimeout (timers.js:250:5)
>     at Timer.listOnTimeout (timers.js:214:5)

**Comment by NorthernMan54** [comment]
Does the name in your config match a zone name ?

If it does you need to change one of them.

If it doesn't can you remove .homebridge/persist and .homebridge/accessories and restart homebridge.

**Comment by abko** [comment]
@NorthernMan54 I solved one part of the problem. My receiver supports a 3rd and 4th zone which I don't use. The both have '-' as name. I now changed them to something unique in the Yamaha setup and it resolved the error.

Unfortunately now I bump into a new error. I am getting the following in the logging:

> Unhandled rejection TypeError: Cannot read property '0' of undefined
>     at Object.basicStatus.getVolume (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/yamaha-nodejs/simpleCommands.js:335:78)
>     at /usr/local/lib/node_modules/homebridge-yamaha/index.js:383:39
>     at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
>     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
>     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:432:57)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
>     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
>     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:454:14)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)

Could it be related to the unused zones?

**Comment by NorthernMan54** [comment]
Just looking at the code around that error message, and it is getting the volume for a zone from the receiver and sending it to home kit.  If you are running in debug mode, it will show which device is was requesting the volume for.  Likely

Looks like this ( this for a switch in my setup )   

May 14 18:56:59 howard homebridge[347]: Sun, 14 May 2017 22:56:59 GMT EventedHTTPServer [::ffff:192.168.1.212] HTTP request: /characteristics?id=3.9
May 14 18:56:59 howard homebridge[347]: Sun, 14 May 2017 22:56:59 GMT HAPServer [CC:22:3D:E3:CE:35] HAP Request: GET /characteristics?id=3.9
May 14 18:56:59 howard homebridge[347]: Sun, 14 May 2017 22:56:59 GMT Accessory [Howard] Getting value for Characteristic "On"
May 14 18:56:59 howard homebridge[347]: [5/14/2017, 6:56:59 PM] [EcoPlug] Getting Status: ECO-7801F87E Office
May 14 18:56:59 howard homebridge[347]: Sun, 14 May 2017 22:56:59 GMT Accessory [Howard] Got Characteristic "On" value: 1
May 14 18:56:59 howard homebridge[347]: Sun, 14 May 2017 22:56:59 GMT EventedHTTPServer [::ffff:192.168.1.212] HTTP Response is finished

The id=3.9 is important as this is how home kit tracks devices.  This is device/accessory 3 and its characteristic 9.   To determine if it is one of your unused zones you would need to look at the id numbers to determine which is which.  A full debug log from startup would show this.

PS I don't have access to my yamaha right now, it is installed at my cottage for the summer.

**Comment by abko** [comment]
I think it must be for zone 4. In the web gui of the Yamaha Zone4 is greyed out. I believe it needs some specific setup to be able to use it (I would not even know how speaker outputs can be hooked up to Zone4). Maybe that explains why the volume is not returned as expected for Zone 4 and maybe there is a way to detect this.

This is the log just before the crash. It stops just before Zone 4. Ideally it would detect zone 3 and 4 not to be active and skip those. Not sure if this is possible.

> YamahaAVR Got volume percent of -42%, 27%  Main_Zone +141ms
>   Accessory [Homebridge] Got Characteristic "Brightness" value: 27 +48ms
>   Accessory [Homebridge] Got Characteristic "On" value: false +47ms
>   YamahaAVR Got volume percent of -42.5%, 25%  Zone_2 +78ms
>   Accessory [Homebridge] Got Characteristic "Brightness" value: 25 +32ms
>   Accessory [Homebridge] Got Characteristic "On" value: false +81ms
>   YamahaAVR Got volume percent of -40%, 33%  Zone_3 +145ms
>   Accessory [Homebridge] Got Characteristic "Brightness" value: 33 +63ms
>   Accessory [Homebridge] Got Characteristic "On" value: false +31ms
> Unhandled rejection TypeError: Cannot read property '0' of undefined
>     at Object.basicStatus.getVolume (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/yamaha-nodejs/simpleCommands.js:335:78)

**Comment by abko** [comment]
@NorthernMan54 I could not find the id=x.y reference in the logging. Would it be possible for the plugin to detect if a Zone is active for a Receiver, or alternatively to specify the number of zones which are active in config.json?
Let me know if there are additional tests you would like me to perform.

**Comment by NorthernMan54** [comment]
@abko As part of the plugin, I ask the receiver for the zone configuration, and set the number of accessories based on the response.  I have added additional debugging, for when it is checking the zone config.  If you could re-install and try again much appreciated.  It should have a long verbose section with your config as part of this.

**Comment by abko** [comment]
Thanks again for all your efforts!

The error message happens when the Home app is trying to access info about the Zone 4 accessory. At least this is my suspicion since it logs about the other zones, but not about the 4th one. 

Below is first the part of logging which contains the returned info from the Receiver. Below that you can find the error message once more.

> [5/16/2017, 7:17:55 AM] Found Yamaha RX-A3060 - 06005753, "AV Receiver"
> {
>   "YAMAHA_AV": {
>     "$": {
>       "rsp": "GET",
>       "RC": "0"
>     },
>     "System": [
>       {
>         "Config": [
>           {
>             "Model_Name": [
>               "RX-A3060"
>             ],
>             "System_ID": [
>               "06005753"
>             ],
>             "Version": [
>               "1.27/2.00"
>             ],
>             "Feature_Existence": [
>               {
>                 "Main_Zone": [
>                   "1"
>                 ],
>                 "Zone_2": [
>                   "1"
>                 ],
>                 "Zone_3": [
>                   "1"
>                 ],
>                 "Zone_4": [
>                   "1"
>                 ],
>                 "Tuner": [
>                   "1"
>                 ],
>                 "DAB": [
>                   "0"
>                 ],
>                 "HD_Radio": [
>                   "0"
>                 ],
>                 "Rhapsody": [
>                   "0"
>                 ],
>                 "Napster": [
>                   "1"
>                 ],
>                 "SiriusXM": [
>                   "0"
>                 ],
>                 "Spotify": [
>                   "1"
>                 ],
>                 "Pandora": [
>                   "0"
>                 ],
>                 "JUKE": [
>                   "1"
>                 ],
>                 "Qobuz": [
>                   "1"
>                 ],
>                 "radiko_jp": [
>                   "0"
>                 ],
>                 "MusicCast_Link": [
>                   "0"
>                 ],
>                 "SERVER": [
>                   "1"
>                 ],
>                 "NET_RADIO": [
>                   "1"
>                 ],
>                 "Bluetooth": [
>                   "1"
>                 ],
>                 "USB": [
>                   "1"
>                 ],
>                 "AirPlay": [
>                   "1"
>                 ]
>               }
>             ],
>             "Name": [
>               {
>                 "Input": [
>                   {
>                     "PHONO": [
>                       "PHONO"
>                     ],
>                     "AV_1": [
>                       "Amino A550"
>                     ],
>                     "AV_2": [
>                       "Videocore"
>                     ],
>                     "AV_3": [
>                       "AV3"
>                     ],
>                     "AV_4": [
>                       "AV4"
>                     ],
>                     "AV_5": [
>                       "AV5"
>                     ],
>                     "AV_6": [
>                       "AV6"
>                     ],
>                     "AV_7": [
>                       "AV7"
>                     ],
>                     "V_AUX": [
>                       "V-AUX"
>                     ],
>                     "AUDIO_1": [
>                       "TV"
>                     ],
>                     "AUDIO_2": [
>                       "AUDIO2"
>                     ],
>                     "AUDIO_3": [
>                       "AUDIO3"
>                     ],
>                     "USB": [
>                       "USB"
>                     ]
>                   }
>                 ]
>               }
>             ]
>           }
>         ]
>       }
>     ]
>   }
> }


See error when trying to access the Zone 4 accessory in the Home app:

> YamahaAVR Got volume percent of -40%, 33%  Zone_3 +202ms
>   Accessory [Homebridge] Got Characteristic "Brightness" value: 33 +74ms
> Unhandled rejection TypeError: Cannot read property '0' of undefined
>     at Object.basicStatus.getVolume (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/yamaha-nodejs/simpleCommands.js:335:78)
>     at /usr/local/lib/node_modules/homebridge-yamaha/index.js:383:39
>     at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
>     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
>     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:432:57)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
>     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
>     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:454:14)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
>

**Comment by NorthernMan54** [comment]
In the debug output, it shows that all 4 zones are available, but nothing jumped out about the volume. What I'm going todo tonight is add debugging on the volume call, so we can see exactly what is returned for zone 4.  Once I have that I will have volume call bypass that zone.

**Comment by abko** [comment]
Thanks a lot. I shall load the update after that and share the results asap afterwards!

**Comment by NorthernMan54** [comment]
@abko Please try again and post the results.  I added more debugging output around the volume call, and also added error trapping for the issue.  Fingers crossed it should now work correctly.

If this works, I'm going to take a look at the debug output, and see if I can have the plugin ignore your Zone 4 based on the lack of volume control.

**Comment by abko** [comment]
@NorthernMan54 Thanks again! I am adding the log as attachment. It lists the data for zones a couple of times, also for Zone 4. There is some repetition for the data, not sure if that is the intension. 
The error message stopped appearing, so the added error trapping is helping!

Note that the first 4 blocks happen during initial setup of homebridge and only show Main_zone. The 2nd block I copied from the log that happens when I view the accessories in the Home app on my Phone (I put some extra line breaks in the log to split them).

[log.txt](https://github.com/neonightmare/homebridge-yamaha/files/1006677/log.txt)

**Comment by NorthernMan54** [comment]
@abko Tks, this log shows exactly what is happening with Zone 4, and highlights that while being supported, it does not include a Volume control.

I'm going to use this to update my zone detection logic, and have it only create an accessory when the zone supports a volume control.  This should take a day or 2.

Did the created accessories work properly?

**Comment by abko** [comment]
Yes, they do, although like with the master version, Volume changes are not always being picked up. 

Thanks again for your great help and work on the plugin!

A bit of a side topic, but would it be a possibility to have an accessory per input of the Yamaha in order to do input selection, or is that a bit clumsy?
I have no experience (yet) with JavaScript/ Node.js, but I am considering to study a bit how I can make changes/ improvements myself so I can also contribute to various plugins (I have done C, C++ and Objective C programme a long time ago).

**Comment by NorthernMan54** [comment]
The oddness of the volume, is related to how HomeKit sends updates for when the volume changes ( If have seen this with other plugins as well ).   HomeKit is event driven so  multiple updates can be sent to the device at the same time, and the device gets confused when it sees multiple updates in a short period of time, in no particular order.   I have tried a couple of levelling approaches, but nothing has really worked well.  The only one I have been reasonably with, was changing the slider to only send updates when the change is > 5%.

For adding additional controls, this is very straight forward, but the challenge is mapping the device control's to the Home apps widgets.  The home app widgets are very limited, and don't map very well to a stereo.  Hence my use of the the lightbulb as a zone control, and individual switches as tuner preset buttons.  You could create a switch per input, and end up with about a dozen switches.

For coding, I was like you about 12 months ago, and very quickly picked up nodejs/JavaScript. The biggest challenge being the event driven programming model in nodejs, and callbacks.  Once you wrap your head around those two concepts it is straight forward.

**Comment by NorthernMan54** [comment]
@abko Okay have moved all the verbose logging to debug mode, and have added logic to only create a Zone volume control for zones that support volume.   PS I don't have access to my yamaha, so I haven't tested this.  Good luck

Also to add input support, take a look at the section of code around radio presents, this is close to how inputs could be coded.

**Comment by abko** [comment]
@NorthernMan54 I am receiving some errors now, see attached log.
[log2.txt](https://github.com/neonightmare/homebridge-yamaha/files/1009835/log2.txt)

Sorry, I did not have time to remove my other plugins so there a lot of info in the log.

In my HomeApp I only see the AV receiver accessory and the one for the mainzone.

Let me know if I can do some more digging.

**Comment by abko** [comment]
Thanks again for all efforts. This eventing I will also try input control. Thanks!

**Comment by florian-muc** [comment]
Hi guys, I am silently following your discussion and I'm also playing with the recent changes. First of all: thanks for picking up work on this plug-in, really happy to see increasing support for my Yamaha receiver through homebridge!
I updated to the latest git version (including the node-js module) and tried playing with the plug-in, however I've always been struggling to get most features to work. My receiver is a RX-V575, my go-to HomeKit app is Eve (as I'm working on it), but I also play around with others.

- I do see the Input Functions service with the string characteristic showing the selected input., so that works fine. However, it would be really awesome being able to select a different input. Even an array of switches would be fine as a starting point.
- I've never been able to get play_volume or setMainInputTo to work, the receiver always starts with the previously set input and volume. Does this work for others?
- I also can't get the radio_presets to show up at all. One thing I'm just noticing right now: do I need to add preset_num to the config when adding radio_presets?
- On a more philosophical level, I'm not a huge fan of using a Lightbulb service for controlling volume and power state. HomeKit has support for a Speaker service that offers everything needed. The fact that Home app is limited should not guide the design of an accessory, rather should all of us file enhancement requests with Apple. Plus, WWDC is only a few weeks out. I expect major changes in Home app, since it will be the first iteration since initially shipping Home app.

**Comment by NorthernMan54** [comment]
@abko fixed, wrong variable

**Comment by abko** [comment]
I still only get an accessory for the main zone. Also there is an error message being shown. Something might still be off for zone 2-4:

> Unhandled rejection TypeError: this.log is not a function
>     at /usr/local/lib/node_modules/homebridge-yamaha/index.js:161:62
>     at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
>     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
>     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:454:14)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:668:14)
>     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:694:18)
>     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
>     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:432:57)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
> 
> Unhandled rejection TypeError: this.log is not a function
>     at /usr/local/lib/node_modules/homebridge-yamaha/index.js:161:62
>     at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
>     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
>     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:454:14)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:668:14)
>     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:694:18)
>     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
>     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:432:57)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
> 
> Unhandled rejection TypeError: this.log is not a function
>     at /usr/local/lib/node_modules/homebridge-yamaha/index.js:161:62
>     at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
>     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
>     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:454:14)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:668:14)
>     at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:694:18)
>     at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
>     at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:432:57)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
>     at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)

**Comment by NorthernMan54** [comment]
Yes you are correct a missing bind this.   This is one of challenges with JavaScript, callbacks and variable scope.  During the callback, 'this' is not included in the scope, and need to bind it.  Let me make the changes and post again.

**Comment by abko** [comment]
Thanks. It's good for me to witness, so I can learn :-) I started a bit of reading into Node.js, so maybe I can contribute more in future.

**Comment by NorthernMan54** [comment]
@florian-muc 

I'm targeting using this with the Home app and Alexa and they don't support the same rich functionality as Eve, hence controlling a stereo via a light bulb.  If home supported a speaker, I would convert.

For radio presets to work you need to add just 'radio_presets': True to the config.

**Comment by NorthernMan54** [comment]
@abko I have fixed the issues, and tested it against my Yamaha this time.  It should now be working.  Please reinstall and retest.

**Comment by abko** [comment]
@NorthernMan54 Thanks, I tested it and it works. Zone 3 is included, since it has volume control. I am actually not using it, so I like the idea of having an option to disable a zone, e.g. by configuring a number of used zones or by skipping Zones with the default name '-'. Maybe I'll play around with a local clone to try.

I realize I have hijacked this Issue for other purposes. Are there any plans to work towards a new main master for this plugin or is that up to the original owner of the plugin?

@florian-muc Cool to be in contact with one of the people involved with Eve. It's a nice app, and I like the Elgato Eve devices I have in my home setup :-)
I am also hoping for more Homekit improvements by Apple being announced at the WWDC. Although I am considering to dig into Node.js and try some local changes to the plugin for input selection, it might indeed be wise to wait until WWDC in order to make changes based on the latest Homekit improvements.
Maybe it's an option to make choice of a speaker or lightbulb a configurable item if reasons remain to want both depending on the preferred app.

**Comment by jata1** [comment]
@NorthernMan54 Thanks for all the great work on this plug-in. looks like you have solved a number of issues with multi-zone support. 

I noticed that apple will include a new accessory for a speaker in iOS 11 / home app. I know iOS 11 is early beta at the moment but I was hoping that you would look into incorporating this accessory when iOS 11 is released. Can you confirm?

**Comment by NorthernMan54** [comment]
I have been watching this as well, and if it is supported I will switch over.

**Comment by jata1** [comment]
great. thanks again for the awesome work on this plugin.

Can you confirm what i need to install (from git v npm) to get everything working currently. 

yamaha-homebridge - manual install of your fork from git
nodejs-HAP ?
yamaha-nodejs ?

**Comment by NorthernMan54** [comment]
If you have a running homebridge, you can install my forked version with the following command

sudo npm install -g https://github.com/NorthernMan54/homebridge-yamaha

**Comment by jata1** [comment]
thanks. I already have homebridge running for many months - working perfectly with my nest thermostat. I don't want to break this.

If i install your homebridge-yamaha will it install correct versions of dependencies - nodejs-HAP (or hap-nodejs) and yamaha-nodejs?

do I need to be at a specific file location in the CLI when i run the npm install or does the -g flag handle this as a global install for the plug-in?

sorry for these noob questions and your help. Much appreciated!

**Comment by jata1** [comment]
one more thing... My aim for is to have two icons/devices showing in my home app as follows:

Zone 2 set to net radio with volume set to x
Zone 2 set to airplay with volume set to y

Is this possible with the plug-in currently?

**Comment by NorthernMan54** [comment]
Installation

I usually do it from the home directory, but the -g installs it into the correct location.

I creates multiple accessories, of which a couple will be named to match your zones.  With these devices you will be able to turn on/off and control volume. I haven't done anything yet in regards to input selection yet, so you will need to use the Yamaha app for that.

**Comment by jata1** [comment]
OK. massive thanks.

**Comment by abko** [comment]
@NorthernMan54 Thanks a lot. 

I just tested your fork. I have not yet moved to the iOS beta, plan to wait for a few more Beta's. With the Eve App I can see the Speaker, but it currently only appears in in the room where I placed the second Zone accessory, not in the room where the accessory for the first zone is. I will do some more testing (just tried for a couple of minutes). Also I still see the lightbulb accessory as well. It would be nice to only have the Speaker controls, so if I tell Siri to switch on or off all lights my Amp remains powered :-)

**Comment by NorthernMan54** [comment]
Regarding the zones as light bulbs, as soon as the Home app supports speakers I'm going to make the change.   But I'm not holding my breath on it.  I have been watching the discussion around HomeKit after wwwdc and the changes but speaker support has not appeared besides in the kickoff speech.

**Comment by NorthernMan54** [comment]
Your other comment regarding rooms.  I put my eve speaker in the closet and my zones in each room without issue.   Is there something I'm missing here.

Ps I have a room called closet where I put all the unused or don't touch devices.

**Comment by abko** [comment]
@NorthernMan54 I was away for work for a couple of days on a busy trip and browsed through these message a bit to hasty. I thought you made some changes in your fork, but I misread this thread :-)
I incorrectly assumed there was an update, so I installed the latest fork and had the impression there were changes. I noticed the speaker accessory was only in the 2nd zone when using the Eve app. This is likely since I did that myself a while ago.

Let's see if and how Apple will support a Speaker from the Home app. It would be nice if they support it and even include some logic to select an input, but that might be wishful thinking. I'll probably switch to a public beta per mid July to see if I can notice changes that would enable having a speaker accesory per zone controllable from the Home app.

Sorry for the confusion. Until Apple makes changes I am already enjoying the current plugin a lot!

**Comment by unknownset** [comment]
@NorthernMan54 
I'm trying to install your fork. I'm getting this error:

`
Unhandled rejection TypeError: Cannot read property 'YAMAHA_AV' of null
    at YamahaAVRPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha/index.js:136:34)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:668:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
`

I have no clue how to solve it. Do you have any idea?
Thanks a lot!

**Comment by NorthernMan54** [comment]
Question did homebridge exit after the error or keep going?

**Comment by unknownset** [comment]
It keeps going. But it doesn't seem to properly work. The devices are stuck in HomeKit.

**Comment by NorthernMan54** [comment]
That error is what comes out when the discovery process finds a device that isn't a supported Yamaha receiver.  I'm wondering if your receiver is supported?  The interface that the plugin is based on, is the one used by the basic website on the receiver.  Does your support that?

**Comment by unknownset** [comment]
Hmm what you mean exactly by "basic website on the receiver"?
It's a RX-V481. I can access the setup interface at http://192.168.1.101/Setup/index.html
The homebridge-plugin by neonightmare works just fine but I wanted to use yours because of the additional features.

If I can make it work I would add stateless programmable switches for scenes buttons. I can activate scenes by calling:
`<YAMAHA_AV cmd="PUT"><Main_Zone><Scene><Scene_Load>Scene 1</Scene_Load></Scene></Main_Zone></YAMAHA_AV>`

But first I have to fix the problem there.

**Comment by NorthernMan54** [comment]
I think the error is elsewhere, and this may be a red herring, likely another device on your network.  Can you restart in DEBUG mode and share the log.  I didn't make a lot of changes around device discovery so it should have just worked.

**Comment by unknownset** [comment]
Thank you for helping me.
[log.txt](https://github.com/neonightmare/homebridge-yamaha/files/1180817/log.txt)

I attached the full log.
I already tried deleting the cache accessories.

I also tried to clean my config.json and use the sample one. Same result

**Comment by NorthernMan54** [comment]
Thanks for that output, looking at the log it did find your receiver and set it up.   But I believe the issue is that you don’t see the light bulb that allows you to turn on, off and control the volume.  In the code is this line

// Only add zones control if more than 1 zone
                                if (zones.length > 1) {

That only activates the feature if you have more than 1 zone.   So I just went and changed it to greater than 0.  So it should now work for you.  Please re-install and try again.

**Comment by unknownset** [comment]
Thanks. It didn't fix the error, but it now works correctly 👍
Not sure what's happening but to me is fine enough.
Thanks for your support!

**Comment by NorthernMan54** [comment]
That message is a different device responding to the discovery request.  Mine does the same.

**Comment by pimviergever** [comment]
Hi, thx for the great work on this fork!

2 questions: 

1. Why does it show up as a bulb?

2. Homebridge keeps running but I get the following information:

```
Found Yamaha RX-V675 - 0AC28413, "Yamaha"
Unhandled rejection TypeError: zonesXML[prop].includes is not a function
    at /usr/local/lib/node_modules/homebridge-yamaha/node_modules/yamaha-nodejs/simpleCommands.js:481:56
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:668:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/timers.js:26:46)
    at Timer.listOnTimeout (timers.js:92:15)

HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.

```

What's going wrong?

**Comment by NorthernMan54** [comment]
Why does it show up as a lightbulb?  In my fork I had the zone appear as a lightbulb as the Home app didn’t support a speaker.  I looked thru the available widgets in the Home app, and it seemed that it supported controlling a stereo/zone best.   You can turn it on or off, and change the volume by changing the brightness.   As a added bonus, it also worked with my version of homebridge that supports Alexa.

As I mostly control the stereo with Alexa, that is a lightbulb never comes up.

The unhandled rejection exeception is caused by the discovery process, and it seeing another device on the network that isn’t a Yamaha Receiver.  As it doesn’t cause an issue, I just ignore it.

**Comment by chriskmn** [comment]
Hi,

I installed the module with Node v8.5.0, npm v5.4.2 and homebridge v0.4.28.
I get the following error message after installing the module:

> Sep 30 21:36:06 Orangepi homebridge[7598]: /usr/bin/node[7598]: ../src/cares_wrap.cc:1944:void node::cares_wrap::{anonymous}::GetAddrInfo(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[4]->IsBoolean()' failed.
Sep 30 21:36:06 Orangepi homebridge[7598]:  1: node::Abort() [homebridge]
Sep 30 21:36:06 Orangepi homebridge[7598]:  2: node::Assert(char const* const (*) [4]) [homebridge]
Sep 30 21:36:06 Orangepi homebridge[7598]:  3: 0x127e568 [homebridge]
Sep 30 21:36:06 Orangepi homebridge[7598]:  4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [homebridge]
Sep 30 21:36:06 Orangepi homebridge[7598]:  5: 0xbaa800 [homebridge]
Sep 30 21:36:06 Orangepi systemd[1]: homebridge.service: Main process exited, code=killed, status=6/ABRT
Sep 30 21:36:06 Orangepi systemd[1]: homebridge.service: Unit entered failed state.
Sep 30 21:36:06 Orangepi systemd[1]: homebridge.service: Failed with result 'signal'.
> 

These are my modules:

> /usr/local/lib
+-- bindings@1.3.0
+-- broadlinkjs-sm@0.1.5
+-- d@1.0.0
+-- forever@0.15.3
+-- hap-nodejs@0.4.33
+-- homebridge@0.4.28
+-- homebridge-better-http-rgb@1.0.0
+-- homebridge-broadlink-platform@0.1.0
+-- homebridge-mqtt-humidity-tasmota@0.1.2
+-- homebridge-mqtt-switch-tasmota@0.9.5
+-- homebridge-mqtt-temperature-log-tasmota@1.0.1
+-- homebridge-mqtt-temperature-tasmota@0.9.2
+-- homebridge-samsungtv-control@1.1.1
+-- homebridge-yamaha@0.0.5-alpha.1 (git+https://github.com/NorthernMan54/homebridge-yamaha.git#57c2fd1fb5bc8b2f0b36b5be2360659069d34029)
+-- node-gyp@3.6.2
`-- npm@5.4.2
> 

Any ideas on this ?

Thanks for helping, Chris

**Comment by chriskmn** [comment]
`Sep 30 21:36:06 Orangepi homebridge[7598]: /usr/bin/node[7598]: ../src/cares_wrap.cc:1944:void node::cares_wrap::{anonymous}::GetAddrInfo(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[4]->IsBoolean()' failed.
Sep 30 21:36:06 Orangepi homebridge[7598]:  1: node::Abort() [homebridge]
Sep 30 21:36:06 Orangepi homebridge[7598]:  2: node::Assert(char const* const (*) [4]) [homebridge]
Sep 30 21:36:06 Orangepi homebridge[7598]:  3: 0x127e568 [homebridge]
Sep 30 21:36:06 Orangepi homebridge[7598]:  4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [homebridge]
Sep 30 21:36:06 Orangepi homebridge[7598]:  5: 0xbaa800 [homebridge]
Sep 30 21:36:06 Orangepi systemd[1]: homebridge.service: Main process exited, code=killed, status=6/ABRT
Sep 30 21:36:06 Orangepi systemd[1]: homebridge.service: Unit entered failed state.
Sep 30 21:36:06 Orangepi systemd[1]: homebridge.service: Failed with result 'signal'.
`

**Comment by NorthernMan54** [comment]
@chriskmn Unfortunately that error isn’t descriptive enough to indicate where the problem lies.  Are you sure it’s caused by this plugin?  If it is, I would suggest starting homebridge outside of systemd, from the command line so the error is better displayed.

**Comment by chriskmn** [comment]
@NorthernMan54 Yes it definately worked without problems before installing the module. I wil try to get better debug information. Thanks, Chris

follow up: I wasn‘t able to get deeper info. The Yamaha module initializes properly but there seems to be something in the code like a type mismatchn of variables. May be it is linked to the new versions of node and npm on my system.

Would be interesting if anybody has a working yamaha on node 8.5.x and npm 5.4.x

**Comment by chriskmn** [comment]
after downgrading Nodejs to v6.11.3 i still get error message:

> 

Oct 01 19:22:01 Orangepi homebridge[5602]: [10/1/2017, 7:22:01 PM] ---
Oct 01 19:22:01 Orangepi homebridge[5602]: [10/1/2017, 7:22:01 PM] Loaded plugin: homebridge-samsungtv-control
Oct 01 19:22:01 Orangepi homebridge[5602]: [10/1/2017, 7:22:01 PM] Registering accessory 'homebridge-samsungtv.SamsungTV'
Oct 01 19:22:01 Orangepi homebridge[5602]: [10/1/2017, 7:22:01 PM] ---
Oct 01 19:22:04 Orangepi homebridge[5602]: [10/1/2017, 7:22:04 PM] ====================
Oct 01 19:22:04 Orangepi homebridge[5602]: [10/1/2017, 7:22:04 PM] ERROR LOADING PLUGIN homebridge-yamaha:
Oct 01 19:22:04 Orangepi homebridge[5602]: [10/1/2017, 7:22:04 PM] Error: Module version mismatch. Expected 48, got 57.
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Error (native)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Object.Module._extensions..node (module.js:597:18)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Module.load (module.js:487:32)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at tryModuleLoad (module.js:446:12)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Function.Module._load (module.js:438:3)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Module.require (module.js:497:17)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at require (internal/module.js:20:19)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/mdns/lib/dns_sd.js:24:20)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Module._compile (module.js:570:32)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Object.Module._extensions..js (module.js:579:10)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Module.load (module.js:487:32)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at tryModuleLoad (module.js:446:12)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Function.Module._load (module.js:438:3)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Module.require (module.js:497:17)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at require (internal/module.js:20:19)
Oct 01 19:22:04 Orangepi homebridge[5602]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha/node_modules/mdns/lib/mdns.js:1:77)

>

**Comment by NorthernMan54** [comment]
The important part of that error message is

PM] Error: Module version mismatch. Expected 48, got 57.

Which is a frequent issue after changing versions of nodejs.  If you google it, you will see a lot of people hiting this after changing versions.  Try

sudo npm rebuild


> On Oct 1, 2017, at 1:25 PM, Chris <notifications@github.com> wrote:
> 
> PM] Error: Module version mismatch. Expected 48, got 57.


.

**Comment by chriskmn** [comment]
@NorthernMan54 thank you, that helped me to align NPM version with node. Rebuild put npm back to v3.10.10

BUT with this new setup (node v6 and npm v3) I got the same error as in the beginning with node v8:

>
Oct 01 21:17:27 Orangepi homebridge[23550]: /usr/bin/node[23550]: ../src/cares_wrap.cc:1944:void node::cares_wrap::{anonymous}::GetAddrInfo(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[4]->IsBoolean()' failed.
Oct 01 21:17:27 Orangepi homebridge[23550]:  1: node::Abort() [homebridge]
Oct 01 21:17:27 Orangepi homebridge[23550]:  2: node::Assert(char const* const (*) [4]) [homebridge]
Oct 01 21:17:27 Orangepi homebridge[23550]:  3: 0x127ebe8 [homebridge]
Oct 01 21:17:27 Orangepi homebridge[23550]:  4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [homebridge]
Oct 01 21:17:27 Orangepi homebridge[23550]:  5: 0xbab140 [homebridge]
Oct 01 21:17:27 Orangepi systemd[1]: homebridge.service: Main process exited, code=killed, status=6/ABRT
Oct 01 21:17:27 Orangepi systemd[1]: homebridge.service: Unit entered failed state.
Oct 01 21:17:27 Orangepi systemd[1]: homebridge.service: Failed with result 'signal'.
>

May be it is related to my arm64 architecture which might be not so much supported

**Comment by NorthernMan54** [comment]
Humm after a bit more googling I saw this

https://github.com/agnat/node_mdns/issues/199

This is your error, and it looks like it was fixed a couple of hours ago, but has not been published yet.

Also double check your versions, as that error started with Node 8.5.  At this time the best version for homebridge is 6.11.3.  What does your machine show for these commands?

**node -v**
v6.11.3
**nodejs -v**
v6.11.3
**npm -v**
3.10.10

**Comment by chriskmn** [comment]
I had exactly that setup. By the way the Tool „NVM“ is really great to switch between node versions. Very reccomended !

I will check your link. Thanks a lot @NorthernMan54

**Comment by chriskmn** [comment]
finally I got it working !

Proböem was: with the NVM Node version manager I got a second NPM and Node installed and the old one was not deleted. Homebridge worked with the first installation (8.6.0).

So after cleaning all up and reinstalling Node v6.11.3 with NPM v3.10.10 the plugin is working now.

Thanks again for your help !

**Comment by NorthernMan54** [comment]
Glad to hear that you got everything working

Enjoy

**Comment by chriskmn** [comment]
If I may ask another question... :-)

Oct 02 19:54:32 Orangepi homebridge[26358]: Unhandled rejection TypeError: Cannot read property 'YAMAHA_AV' of null
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-yamaha/index.js:136:34)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at tryCatcher (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/util.js:16:23)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:512:31)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:614:10)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:693:18)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:454:14)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._fulfillPromises (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:668:14)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._settlePromises (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:694:18)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._fulfill (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:638:18)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._resolveCallback (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:432:57)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:524:17)
Oct 02 19:54:32 Orangepi homebridge[26358]:     at Promise._settlePromise (/usr/lib/node_modules/homebridge-yamaha/node_modules/bluebird/js/release/promise.js:569:18)
Oct 02 19:54:33 Orangepi homebridge[26358]: [10/2/2017, 7:54:33 PM] [YamahaAVR] Found Yamaha RX-V677 - 039F98E3, "RX-V677"
Oct 02 19:54:33 Orangepi homebridge[26358]: Unhandled rejection TypeError: Cannot read property 'YAMAHA_AV' of null

Does anyone know how to fix this ?

My config.json is:
`{
        "platform": "YamahaAVR", 
		"play_volume": -48,
		"set_input_to": "Airplay",
		"zones_as_accessories": { 
			"YAMAHA_AV": { 
				"1": { 
					"name": "Main" 
					}, 
				"2": { 
					"name": "Zone 2" 
					}
				}
			}
		}`

**Comment by NorthernMan54** [comment]
Is the plugin working?

If yes, then those messages are from the plugin asking other devices are they a Yamaha receiver and can be ignored

**Comment by chriskmn** [comment]
Yes it is working fine.

Thank you for the info. So it seems that I am done :-))))

**Comment by abko** [comment]
Hi all, I had to do a clean install on my Raspberry and am a bit confused about what fork to use at the moment. It would be great to be able to control two zones (switch a zone on/off), have volume control and be able to select an input. I have the impression a number of forks aim to make that possible, but I am not sure what fork to use and what config.json settings to drive those options in each fork. Is it basically still work in progress or could someone recommend a fork to work with already?

**Comment by NorthernMan54** [comment]
@abko My fork is optimized for usage from the Home app, and only supports Zone's, Volume and Radio presets.  It doesn't support changing inputs.

npm install https://github.com/NorthernMan54/homebridge-yamaha

**Comment by abko** [comment]
@NorthernMan54 Thanks. I am using your fork again, and will stick to the Yamaha app to change inputs. Nice to see volume working well now!

**Comment by ArtemDyachuk** [comment]
Hi, is there any way to activate Party Mode instead (or additionally) to Zone 2?

**Comment by MartinGranados** [comment]
@NorthernMan54 i have just installed your fork and ill be checking it out. I tried to install @aficustree version since his has the option for a speaker icon but i couldnt get it to work. Do you think youd have the time to implement a speaker icon instead of bulb?

**Comment by aficustree** [comment]
Sorry @offthahorse , turns out the speaker widget is only for audio enabled cameras. Apparently a proper speaker widget is waiting on AirPlay2. I’ll look at it then. The whole code base is a bit of a mess in need of a refactor.
